name: 'Continuous Deployment'

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1
  SERVICE: inference-ml-model
  REGION: us-central1

jobs:
  deploy:
    # Only run if CI workflow completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Configure Docker to use gcloud as a credential helper'
        run: |
          gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/flask-ml-model:$GITHUB_SHA .
          docker build -t gcr.io/$PROJECT_ID/flask-ml-model:latest .

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/$PROJECT_ID/flask-ml-model:$GITHUB_SHA
          docker push gcr.io/$PROJECT_ID/flask-ml-model:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image gcr.io/$PROJECT_ID/flask-ml-model:$GITHUB_SHA \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --set-env-vars MODEL_PATH=gs://modelos-mlflow/doubleit-model.pt \
            --memory 2Gi \
            --cpu 1 \
            --max-instances 10 \
            --min-instances 0 \
            --port 8080

      - name: Show service URL
        run: |
          gcloud run services describe $SERVICE --platform managed --region $REGION --format 'value(status.url)'
