name: 'Continuous Integration'

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' 
      
      - name: Create virtual environment and install dependencies
        run: |
          python3.12 -m pip install --user virtualenv
          python3.12 -m virtualenv .venv
          . .venv/bin/activate
          make install

      - name: Run model tests
        run: |
          . .venv/bin/activate
          make model-test

      - name: Run API tests
        run: |
          . .venv/bin/activate
          make api-test